//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquidEyes.ESignatures.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SquidEyes.ESignatures.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-mail.com
        ///027168.com
        ///0815.ru
        ///0815.ry
        ///0815.su
        ///0845.ru
        ///0box.eu
        ///0clickemail.com
        ///0n0ff.net
        ///0nelce.com
        ///0v.ro
        ///0w.ro
        ///0wnd.net
        ///0wnd.org
        ///0x207.info
        ///1-8.biz
        ///1-tm.com
        ///10-minute-mail.com
        ///1000rebates.stream
        ///100likers.com
        ///105kg.ru
        ///10dk.email
        ///10mail.com
        ///10mail.org
        ///10minut.com.pl
        ///10minut.xyz
        ///10minutemail.be
        ///10minutemail.cf
        ///10minutemail.co.uk
        ///10minutemail.co.za
        ///10minutemail.com
        ///10minutemail.de
        ///10minutemail.ga
        ///10minutemail.gq
        ///10minutemail.ml
        ///10minutemail.net
        ///10minutemail.nl
        ///10minutemail. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlockedDomains {
            get {
                return ResourceManager.GetString("BlockedDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Version 2022120200, Last Updated Fri Dec  2 07:07:01 2022 UTC
        ///AAA
        ///AARP
        ///ABARTH
        ///ABB
        ///ABBOTT
        ///ABBVIE
        ///ABC
        ///ABLE
        ///ABOGADO
        ///ABUDHABI
        ///AC
        ///ACADEMY
        ///ACCENTURE
        ///ACCOUNTANT
        ///ACCOUNTANTS
        ///ACO
        ///ACTOR
        ///AD
        ///ADS
        ///ADULT
        ///AE
        ///AEG
        ///AERO
        ///AETNA
        ///AF
        ///AFL
        ///AFRICA
        ///AG
        ///AGAKHAN
        ///AGENCY
        ///AI
        ///AIG
        ///AIRBUS
        ///AIRFORCE
        ///AIRTEL
        ///AKDN
        ///AL
        ///ALFAROMEO
        ///ALIBABA
        ///ALIPAY
        ///ALLFINANZ
        ///ALLSTATE
        ///ALLY
        ///ALSACE
        ///ALSTOM
        ///AM
        ///AMAZON
        ///AMERICANEXPRESS
        ///AMERICANFAMILY
        ///AMEX
        ///AMFAM
        ///AMICA
        ///AMSTERDAM
        ///ANALYTICS
        ///ANDROID
        ///ANQUAN
        ///ANZ
        ///AO
        ///AOL
        ///APARTM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TopLevelDomains {
            get {
                return ResourceManager.GetString("TopLevelDomains", resourceCulture);
            }
        }
    }
}
